[theme]
base = "light"
primaryColor = "#4051b5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6fa"
textColor = "#263238"
font = "sans serif"

[server]
headless = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false
